'use client';

import { Logo } from "@/components/icons";
import Link from "next/link";
import { useEffect } from "react";

export default function TermsPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="flex flex-col min-h-screen bg-[#2d1b4e]">
      <header className="px-4 lg:px-6 h-16 flex items-center justify-center sm:justify-start bg-[#2d1b4e]/80 backdrop-blur-sm sticky top-0 z-50 border-b border-purple-800">
        <Link href="/" className="flex items-center justify-center gap-2" prefetch={false}>
          <Logo className="h-6 w-6 text-purple-300" />
          <span className="text-xl font-semibold font-headline text-white">ColoringPics</span>
        </Link>
      </header>
      
      <main className="flex-1 p-4 sm:p-6 lg:p-8 pt-8 sm:pt-12 lg:pt-16">
        <div className="container mx-auto max-w-4xl">
          <div className="bg-[#1a0d2e]/90 border border-purple-900 rounded-lg p-6 sm:p-8 md:p-12">
            <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
            <p className="text-purple-300 text-sm mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
            
            <div className="space-y-6 text-purple-100">
              <section>
                <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                <p className="mb-2">
                  By accessing and using ColoringPics ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
                <p className="mb-2">
                  ColoringPics is an AI-powered service that converts user-uploaded photographs into coloring book pages. The Service uses artificial intelligence to transform images into line art suitable for coloring.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">3. User-Generated Content</h2>
                <p className="mb-2">
                  You retain all ownership rights to the photographs you upload. By uploading content, you grant ColoringPics a limited, non-exclusive, royalty-free license to:
                </p>
                <ul className="list-disc pl-6 mb-2 space-y-1">
                  <li>Process your images through our AI systems to generate coloring book pages</li>
                  <li>Temporarily store your images during processing</li>
                  <li>Display generated coloring pages to you through our Service</li>
                </ul>
                <p className="mb-2">
                  You are solely responsible for the content you upload. You warrant that you own or have the necessary rights to use all uploaded content and that your use does not violate any third-party rights, including copyright, trademark, privacy, or publicity rights.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">4. AI-Generated Content</h2>
                <p className="mb-2">
                  The coloring book pages generated by our Service are created using artificial intelligence. While we strive for quality, you acknowledge that:
                </p>
                <ul className="list-disc pl-6 mb-2 space-y-1">
                  <li>AI-generated content may not perfectly reflect your original image</li>
                  <li>Results may vary and cannot be guaranteed</li>
                  <li>ColoringPics makes no warranties regarding the quality, accuracy, or suitability of generated content</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">5. Children's Privacy and Use</h2>
                <p className="mb-2">
                  While our Service is designed to create coloring books suitable for children, users must be at least 13 years old to use the Service independently, or have parental consent. Parents or guardians are responsible for supervising children's use of this Service and ensuring they do not upload inappropriate content.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">6. Prohibited Uses</h2>
                <p className="mb-2">You agree not to use the Service to:</p>
                <ul className="list-disc pl-6 mb-2 space-y-1">
                  <li>Upload content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
                  <li>Upload content that violates any third-party rights, including intellectual property, privacy, or publicity rights</li>
                  <li>Upload content containing nudity, violence, or inappropriate material</li>
                  <li>Upload content that infringes upon copyrights or trademarks</li>
                  <li>Attempt to reverse engineer, copy, or extract the Service's algorithms or technology</li>
                  <li>Use the Service for any commercial purpose without express written permission</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
                <p className="mb-2">
                  The Service, including its software, design, trademarks, and proprietary AI technology, is owned by ColoringPics and protected by copyright and other intellectual property laws. The coloring pages generated are provided for your personal, non-commercial use.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">8. Disclaimer of Warranties</h2>
                <p className="mb-2">
                  THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. ColoringPics does not guarantee that the Service will be uninterrupted, error-free, or free from viruses or other harmful components.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
                <p className="mb-2">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, ColoringPics AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES RESULTING FROM YOUR USE OF THE SERVICE.
                </p>
                <p className="mb-2">
                  IN NO EVENT SHALL ColoringPics'S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRIOR TO THE ACTION GIVING RISE TO THE LIABILITY, OR $100, WHICHEVER IS GREATER.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">10. Indemnification</h2>
                <p className="mb-2">
                  You agree to defend, indemnify, and hold harmless ColoringPics, its officers, directors, employees, and agents from and against any claims, actions, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from your use of the Service or violation of these Terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">11. Data Storage and Retention</h2>
                <p className="mb-2">
                  You acknowledge that uploaded images and generated content may be temporarily stored for processing purposes. ColoringPics will delete user data in accordance with our Privacy Policy. We are not responsible for loss of data due to technical failures or security breaches.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">12. Changes to Terms</h2>
                <p className="mb-2">
                  ColoringPics reserves the right to modify these Terms at any time. We will notify users of any material changes by posting the new Terms on this page and updating the "Last updated" date. Your continued use of the Service after such modifications constitutes acceptance of the updated Terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">13. Termination</h2>
                <p className="mb-2">
                  ColoringPics reserves the right to terminate or suspend your access to the Service immediately, without prior notice, for any breach of these Terms or for any other reason at our sole discretion.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">14. Governing Law</h2>
                <p className="mb-2">
                  These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which ColoringPics operates, without regard to its conflict of law provisions.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-3">15. Contact Information</h2>
                <p className="mb-2">
                  If you have any questions about these Terms, please contact us through the Service.
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>

      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-purple-800">
        <p className="text-xs text-purple-300">&copy; 2025 ColoringPics. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="/terms" className="text-xs text-purple-300 hover:text-purple-200 hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="/privacy" className="text-xs text-purple-300 hover:text-purple-200 hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  );
}

